/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uem.clinica.viewSec;
import com.uem.clinica.entidades.Paciente;
import com.uem.clinica.entidades.Secretaria;
import java.util.ArrayList;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ListarPacientes extends javax.swing.JInternalFrame {
    private Secretaria sec;
    private String[] colunas = {"ID", "Nome", "Data Nasc", "Endereço", "Celular", "Email"};
    private DefaultTableModel tableModel = new DefaultTableModel(colunas, 0);
            
    /**
     * Creates new form CreateAppointmentPage
     */
    public ListarPacientes(EntityManagerFactory emf) {
        initComponents();
        jTable1.setPreferredScrollableViewportSize(jTable1.getPreferredScrollableViewportSize());
        
        this.sec = new Secretaria(emf);
        
        ArrayList<Paciente> lista = sec.listarPacientes();
        
        for(Paciente p: lista) {
            Object[] ob = {p.getId(), p.getNome(), p.getDataNascimento().toString(), p.getEndereco().toString(), p.getCelular(), p.getEmail()};
            tableModel.addRow(ob);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Listar Pacientes");

        jTable1.setModel(tableModel);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
