/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uem.clinica.view;

import com.uem.clinica.viewSec.UpdateAppointmentPage;
import com.uem.clinica.viewSec.UpdatePatientPage;
import com.uem.clinica.viewSec.CriarPacienteView;
import com.uem.clinica.viewSec.CriarConsultaView;

import com.uem.clinica.entidades.Medico;
import com.uem.clinica.entidades.Paciente;
import com.uem.clinica.viewSec.ListarPacientes;
import java.awt.Component;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class MainInterface extends javax.swing.JFrame {
    /**
     * Creates new form MainPage
     */
    
    private EntityManagerFactory emf;
    
    public MainInterface() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("clinicaPU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        secretarioMenu = new javax.swing.JMenu();
        criarPacienteEscolhaMenu = new javax.swing.JMenuItem();
        listarPacientes = new javax.swing.JMenuItem();
        atualizarPacienteEscolhaMenu = new javax.swing.JMenuItem();
        removerPacienteEscolhaMenu = new javax.swing.JMenuItem();
        criarAgendamentoEscolhaMenu = new javax.swing.JMenuItem();
        atualizarAgendamentoEscolhaMenu = new javax.swing.JMenuItem();
        relatorioAgendamentoEscolhaMenu = new javax.swing.JMenuItem();
        cancelarAgendamentoEscolhaMenu = new javax.swing.JMenuItem();
        medicoMenu = new javax.swing.JMenu();
        criarDadoAdicionalEscolhaMenu = new javax.swing.JMenuItem();
        atualizarDadoAdicionalEscolhaMenu = new javax.swing.JMenuItem();
        removerDadoAdcicionalEscolhaMenu = new javax.swing.JMenuItem();
        criarRelatorioMedicoEscolhaMenu = new javax.swing.JMenuItem();
        atualizarRelatorioMedicoEscolhaMenu = new javax.swing.JMenuItem();
        removerRelatorioMedicoEscolhaMenu = new javax.swing.JMenuItem();
        criarPronturarioEscolhaMenu = new javax.swing.JMenuItem();
        atualizarProntuarioEscolhaMenu = new javax.swing.JMenuItem();
        removerProntuarioEscolhaMenu = new javax.swing.JMenuItem();
        gerarReceitaEscolhaMenu = new javax.swing.JMenuItem();
        gerarAtestadoEscolhaMenu = new javax.swing.JMenuItem();
        gerarDeclaracao = new javax.swing.JMenuItem();
        numPacientesMesEscolha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        secretarioMenu.setText("Secretário");

        criarPacienteEscolhaMenu.setText("Criar Paciente");
        criarPacienteEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPacienteEscolhaMenuActionPerformed(evt);
            }
        });
        secretarioMenu.add(criarPacienteEscolhaMenu);

        listarPacientes.setText("Listar Pacientes");
        listarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPacientesActionPerformed(evt);
            }
        });
        secretarioMenu.add(listarPacientes);

        atualizarPacienteEscolhaMenu.setText("Atualizar Paciente");
        atualizarPacienteEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPacienteEscolhaMenuActionPerformed(evt);
            }
        });
        secretarioMenu.add(atualizarPacienteEscolhaMenu);

        removerPacienteEscolhaMenu.setText("Remover Paciente");
        removerPacienteEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPacienteEscolhaMenuActionPerformed(evt);
            }
        });
        secretarioMenu.add(removerPacienteEscolhaMenu);

        criarAgendamentoEscolhaMenu.setText("Criar consulta");
        criarAgendamentoEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAgendamentoEscolhaMenuActionPerformed(evt);
            }
        });
        secretarioMenu.add(criarAgendamentoEscolhaMenu);

        atualizarAgendamentoEscolhaMenu.setText("Atualizar consulta");
        atualizarAgendamentoEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAgendamentoEscolhaMenuActionPerformed(evt);
            }
        });
        secretarioMenu.add(atualizarAgendamentoEscolhaMenu);

        relatorioAgendamentoEscolhaMenu.setText("Gerar Relatório de Agendamentos");
        secretarioMenu.add(relatorioAgendamentoEscolhaMenu);

        cancelarAgendamentoEscolhaMenu.setText("Cancelar Agendamento");
        secretarioMenu.add(cancelarAgendamentoEscolhaMenu);

        jMenuBar1.add(secretarioMenu);

        medicoMenu.setText("Médico");

        criarDadoAdicionalEscolhaMenu.setText("Definir Paciente");
        criarDadoAdicionalEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarDadoAdicionalEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(criarDadoAdicionalEscolhaMenu);

        atualizarDadoAdicionalEscolhaMenu.setText("Definir Consulta");
        atualizarDadoAdicionalEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarDadoAdicionalEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(atualizarDadoAdicionalEscolhaMenu);

        removerDadoAdcicionalEscolhaMenu.setText("Lista Pacientes");
        removerDadoAdcicionalEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerDadoAdcicionalEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(removerDadoAdcicionalEscolhaMenu);

        criarRelatorioMedicoEscolhaMenu.setText("Adicionar detalhe paciente");
        criarRelatorioMedicoEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarRelatorioMedicoEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(criarRelatorioMedicoEscolhaMenu);

        atualizarRelatorioMedicoEscolhaMenu.setText("Atualizar detalhes paciente");
        atualizarRelatorioMedicoEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarRelatorioMedicoEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(atualizarRelatorioMedicoEscolhaMenu);

        removerRelatorioMedicoEscolhaMenu.setText("Remover detalhes paciente");
        removerRelatorioMedicoEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerRelatorioMedicoEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(removerRelatorioMedicoEscolhaMenu);

        criarPronturarioEscolhaMenu.setText("Criar Prontuário");
        criarPronturarioEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarPronturarioEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(criarPronturarioEscolhaMenu);

        atualizarProntuarioEscolhaMenu.setText("Atualizar Prontuario");
        atualizarProntuarioEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarProntuarioEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(atualizarProntuarioEscolhaMenu);

        removerProntuarioEscolhaMenu.setText("Remover Prontuário");
        removerProntuarioEscolhaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerProntuarioEscolhaMenuActionPerformed(evt);
            }
        });
        medicoMenu.add(removerProntuarioEscolhaMenu);

        gerarReceitaEscolhaMenu.setText("Gerar Receita");
        medicoMenu.add(gerarReceitaEscolhaMenu);

        gerarAtestadoEscolhaMenu.setText("Gerar Atestado");
        medicoMenu.add(gerarAtestadoEscolhaMenu);

        gerarDeclaracao.setText("Gerar declaração");
        medicoMenu.add(gerarDeclaracao);

        numPacientesMesEscolha.setText("N° pacientes atendidos no mês");
        medicoMenu.add(numPacientesMesEscolha);

        jMenuBar1.add(medicoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarPacienteEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPacienteEscolhaMenuActionPerformed
        // Criar Paciente
        CriarPacienteView pg = new CriarPacienteView(emf);
        jDesktopPane1.add(pg);
        pg.setVisible(true);
    }//GEN-LAST:event_criarPacienteEscolhaMenuActionPerformed

    private void criarDadoAdicionalEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarDadoAdicionalEscolhaMenuActionPerformed
        // criar dado adicional

    }//GEN-LAST:event_criarDadoAdicionalEscolhaMenuActionPerformed

    private void atualizarPacienteEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPacienteEscolhaMenuActionPerformed
        // Atualizar Paciente pelo nome:

    }//GEN-LAST:event_atualizarPacienteEscolhaMenuActionPerformed

    private void removerPacienteEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPacienteEscolhaMenuActionPerformed
        // Remover Paciente pelo e-mail:

    }//GEN-LAST:event_removerPacienteEscolhaMenuActionPerformed

    private void criarAgendamentoEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAgendamentoEscolhaMenuActionPerformed
        // criar atendimento

    }//GEN-LAST:event_criarAgendamentoEscolhaMenuActionPerformed

    private void atualizarAgendamentoEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarAgendamentoEscolhaMenuActionPerformed
        // atualizar atendimento

    }//GEN-LAST:event_atualizarAgendamentoEscolhaMenuActionPerformed

    private void atualizarDadoAdicionalEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarDadoAdicionalEscolhaMenuActionPerformed
        // atualizar dado adicional

    }//GEN-LAST:event_atualizarDadoAdicionalEscolhaMenuActionPerformed

    private void removerDadoAdcicionalEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerDadoAdcicionalEscolhaMenuActionPerformed
        // remover dado adicional

        
    }//GEN-LAST:event_removerDadoAdcicionalEscolhaMenuActionPerformed

    private void criarRelatorioMedicoEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarRelatorioMedicoEscolhaMenuActionPerformed
        // relatório médico

    }//GEN-LAST:event_criarRelatorioMedicoEscolhaMenuActionPerformed

    private void atualizarRelatorioMedicoEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarRelatorioMedicoEscolhaMenuActionPerformed
        // atualizar relatório médico

    }//GEN-LAST:event_atualizarRelatorioMedicoEscolhaMenuActionPerformed

    private void removerRelatorioMedicoEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerRelatorioMedicoEscolhaMenuActionPerformed
        // remover relatório médico

    }//GEN-LAST:event_removerRelatorioMedicoEscolhaMenuActionPerformed

    private void atualizarProntuarioEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarProntuarioEscolhaMenuActionPerformed
        //atualizar prontuári

    }//GEN-LAST:event_atualizarProntuarioEscolhaMenuActionPerformed

    private void criarPronturarioEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarPronturarioEscolhaMenuActionPerformed
        // criar prontuário

    }//GEN-LAST:event_criarPronturarioEscolhaMenuActionPerformed

    private void removerProntuarioEscolhaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerProntuarioEscolhaMenuActionPerformed
        // remover prontuário

    }//GEN-LAST:event_removerProntuarioEscolhaMenuActionPerformed

    private void listarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPacientesActionPerformed
        // TODO add your handling code here:
        ListarPacientes lp = new ListarPacientes(emf);
        jDesktopPane1.add(lp);
        lp.setVisible(true);
    }//GEN-LAST:event_listarPacientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem atualizarAgendamentoEscolhaMenu;
    private javax.swing.JMenuItem atualizarDadoAdicionalEscolhaMenu;
    private javax.swing.JMenuItem atualizarPacienteEscolhaMenu;
    private javax.swing.JMenuItem atualizarProntuarioEscolhaMenu;
    private javax.swing.JMenuItem atualizarRelatorioMedicoEscolhaMenu;
    private javax.swing.JMenuItem cancelarAgendamentoEscolhaMenu;
    private javax.swing.JMenuItem criarAgendamentoEscolhaMenu;
    private javax.swing.JMenuItem criarDadoAdicionalEscolhaMenu;
    private javax.swing.JMenuItem criarPacienteEscolhaMenu;
    private javax.swing.JMenuItem criarPronturarioEscolhaMenu;
    private javax.swing.JMenuItem criarRelatorioMedicoEscolhaMenu;
    private javax.swing.JMenuItem gerarAtestadoEscolhaMenu;
    private javax.swing.JMenuItem gerarDeclaracao;
    private javax.swing.JMenuItem gerarReceitaEscolhaMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listarPacientes;
    private javax.swing.JMenu medicoMenu;
    private javax.swing.JMenuItem numPacientesMesEscolha;
    private javax.swing.JMenuItem relatorioAgendamentoEscolhaMenu;
    private javax.swing.JMenuItem removerDadoAdcicionalEscolhaMenu;
    private javax.swing.JMenuItem removerPacienteEscolhaMenu;
    private javax.swing.JMenuItem removerProntuarioEscolhaMenu;
    private javax.swing.JMenuItem removerRelatorioMedicoEscolhaMenu;
    private javax.swing.JMenu secretarioMenu;
    // End of variables declaration//GEN-END:variables
}
